### ISSUE TITLE
Fails with "thread 'main' panicked at 'could not find node path'"

### ISSUE THREAD

**Issue by GoldenretriverYT** [JohnnyMorganz/wally-package-types#6]
I tried to create a project and used aftman to install wally-package-types@1.2.1

When running `wally-package-types --sourcemap sourcemap.json Packages/` I get following output:
```
Mutating Packages/import.lua
Found require in format script/Parent/_Index/vocksel_import@2.1.0/import
thread 'main' panicked at 'could not find node path', src\command.rs:227:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I tried to delete and regenerate the sourcemap but that didnt help. My only wally depedency is `vocksel/import@2.1.0`.

Running on Windows, with Rojo v7.3.0.

Reproduction Workspace:
[test.zip](https://github.com/JohnnyMorganz/wally-package-types/files/11509297/test.zip)

**Comment by LastTalon** [comment]
This was happening for me as well when installing plasma and matter. It turned out to be a problem with the sourcemap being incorrect. After regenerating it it worked as expected.

It would probably be good to catch that as an error more clearly to the user as it causes a lot of confusion for a fairly common issue.

**Comment by JohnnyMorganz** [comment]
Yeah... this tool was hacked together in a few hours and has terrible error handling and reporting

**Comment by JohnnyMorganz** [comment]
Error messages are improved in the latest release
